CREATE DATABASE IF NOT EXISTS leetcode;
USE leetcode;
CREATE TABLE IF NOT EXISTS lc_problem (id INT AUTO_INCREMENT PRIMARY KEY, problem_id INT NOT NULL, description TEXT, scheduled_time DATETIME NOT NULL, comments TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
